services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ${SSL_CERT_FILE}:/cacerts.pem:ro
      - ./jobs/springboot-context-jdk24:/var/jenkins_home/jobs/springboot-context-jdk24
      - ./jenkins-config/hudson.model.JDK.xml:/var/jenkins_home/hudson.model.JDK.xml
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - JAVA_OPTS=-Djavax.net.ssl.trustStore=/opt/java/openjdk/lib/security/cacerts -Djavax.net.ssl.trustStorePassword=changeit
      - JENKINS_INSTALL_PLUGINS=git,github,workflow-aggregator,pipeline-stage-view
    user: root
    command: >
      bash -c "
      if [ -f /cacerts.pem ]; then \
        git config --global http.sslCAinfo /cacerts.pem; \
        git config --global http.sslverify true; \
        echo 'ca-certificate=/cacerts.pem' >> /etc/wgetrc; \
        echo 'check-certificate=on' >> /etc/wgetrc; \
        export SSL_CERT_FILE=/cacerts.pem; \
        apt-get update; \
        echo 'Downloading JDK 24...'; \
        curl -k -L -o /tmp/openjdk-24.tar.gz 'https://github.com/adoptium/temurin24-binaries/releases/download/jdk-24.0.2%2B12/OpenJDK24U-jdk_x64_linux_hotspot_24.0.2_12.tar.gz'; \
        if [ -f /tmp/openjdk-24.tar.gz ]; then \
          mkdir -p /opt/jdk-24; \
          tar -xzf /tmp/openjdk-24.tar.gz -C /opt/jdk-24 --strip-components=1; \
          rm /tmp/openjdk-24.tar.gz; \
          keytool -import -trustcacerts -keystore /opt/jdk-24/lib/security/cacerts -storepass changeit -alias macos-certs -file /cacerts.pem -noprompt; \
        fi; \
      fi && \
      /usr/local/bin/jenkins.sh
      "
volumes:
  jenkins_home:
